# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-renovate-bot

# Trigger the workflow when:
on:
  # When a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches: [master]

jobs:
  add-changelog:
    # NOTE: This name appears in GitHub's Checks API.
    name: add-changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Checkout pull request HEAD commit instead of merge commit.
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set workflow variables
        # Id is needed to access output in a next step.
        id: vars
        run: |
          echo "FILE_NAME=.changelog/${{ github.event.pull_request.number }}.internal.md" >> $GITHUB_OUTPUT
      - name: Create MD file
        run: |
          echo ${{ github.event.pull_request.title }} > ${{ steps.vars.outputs.FILE_NAME }}
      - name: Commit MD file
        run: |
          git config --local user.email "$(git log --pretty='%ae' -1)"
          git config --local user.name "renovate[bot]"
          git add ${{ steps.vars.outputs.FILE_NAME }}
          git commit --amend --no-edit
      - name: Push changes back to branch
        run: |
          git push origin ${{ github.event.pull_request.head.ref }}
