name: CloudFlare

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      - run: yarn build-preview

      - name: Publish to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFRONT_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFRONT_ACCOUNT_ID }}
          projectName: explorer
          directory: build

      - name: Add Comment to PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            🚀 Preview URL: ${{ steps.cloudflare.outputs.url }}
          edit-mode: replace
