# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: release

# Trigger the workflow when:
on:
  # A push occurs to one of the matched tags.
  push:
    tags:
      # Pattern that roughly matches Oasis Core's version tags.
      # For more details on GitHub Actions' pattern match syntax, see:
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags.
      - 'v[0-9]+.[0-9]+*'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn build
      - name: Set workflow variables
        # Id is needed to access output in a next step.
        id: vars
        run: |
          echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Create zip file
        run: |
          cd build/
          zip -r ../oasis-explorer-${{ steps.vars.outputs.SHORT_SHA }}.zip .
      - name: Parse CHANGELOG.md file and extract changes for the given version
        run: |
          node -e '
          const fs = require('fs')
          const changelog = fs.readFileSync('CHANGELOG.md', 'utf8')
          const lines = changelog.split('\n')
          let found = false
          let markdown = ''

          for (const line of lines) {
            if (line.startsWith('## ')) {
              if (found || !line.startsWith(`## ${{ steps.vars.outputs.VERSION }}`)) {
                break
              }
              found = true
            }

            if (found) {
              if (line === `## ${{ steps.vars.outputs.VERSION }}`) {
                break
              }

              const githubIssueLineRegex = /\[#[0-9]+\]\((https:\/\/github\.com\/[^/]+\/[^/]+\/issues\/[0-9]+)\)/
              // line with an issue link starts with multiple whitespaces, but we need only one
              if (line.match(githubIssueLineRegex)) {
                markdown += ` ${line.trim()}`
              } else {
                markdown += line
              }

              // We don't want to add a newline after a title line or when the last char is a comma
              markdown += `${line.startsWith('- ') || line.endsWith(',') ? '' : '\n'}`
            }
          }
          fs.writeFileSync('CHANGELOG_SUMMARY.md', markdown)
          '
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            oasis-explorer-${{ steps.vars.outputs.SHORT_SHA }}.zip
          name: Oasis Explorer ${{ steps.vars.outputs.VERSION }}
          body_path: ${{ github.workspace }}/CHANGELOG_SUMMARY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
