# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: release

# Trigger the workflow when:
on:
  # A push occurs to one of the matched tags.
  push:
    tags:
      # Pattern that roughly matches Oasis Core's version tags.
      # For more details on GitHub Actions' pattern match syntax, see:
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags.
      - 'v[0-9]+.[0-9]+*'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn build
      # Do we want to auto gen changelog here, or do it manually?
      - name: Set up Python 3
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.x'
      - name: Install towncrier
        run: |
          python -m pip install https://github.com/oasisprotocol/towncrier/archive/oasis-master.tar.gz
      # Do we want to use draft option here for change log or action should remove change log fragments?
      - name: Create Change Log draft
        run: |
          towncrier build --draft --version ${{ github.ref_name }} > CHANGELOG_SUMMARY.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/
          # Header of the release.
          name: Oasis Explorer ${{ github.ref_name }}
          # Content generated by Towncrier.
          body_path: ${{ github.workspace }}/CHANGELOG_SUMMARY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
